- null: {}
  general:
  atoms:
    Si: [*, *, *, *, *, 0.76, *, *, *, *, 
         *, *, *, 8.0, 9.0, *, *, *, *, *,
         *, *, *, *, *, *, *, *, *, *,
         *, *]
  bonds:
    H-Si: [250.0, *, *, -0.001, *, *, *, 1.0, 21.0, *,
           *, *, -0.03, 7.5, *, *]
    O-Si: [300.0, 150.0, *, -0.001, *, *, *, 1.0, 20.0, -0.15,
           30.3, *, -0.08, 8.0, *, *]
  offdiagonal:
    H-Si: [0.2, 1.9, 14.0, 1.5, *, *]
    O-Si: [0.2, 2.2, 14.0, 2.2, 1.5, *]
  angles:
    H-O-Si:  [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    H-Si-H:  [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    H-Si-O:  [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    H-Si-Si: [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    O-O-Si:  [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    O-Si-O:  [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    O-Si-Si: [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
    Si-O-Si: [100.0, 40.0, 8.0, *, 4.0, *, 3.0]
  torsions:
  hydrogen:
  info: {VdWtype: Inconsistent, branch: combustion, chargeMethod: EEM, name: ffield_max}
- null: {}
  general:
  atoms:
    Si: [*, *, *, *, *, 0.3, *, *, *, *,
         *, *, *, -1.0, 5.5, *, *, *, *,
         *, *, *, *, *, *, *, *, *, *,
         *, *]
  bonds:
    H-Si: [150.0, *, *, -1.0, *, *, *, 0.1, 0.01, *,
           *, *, -0.15, 4.5, *, *]
    O-Si: [150.0, 5.0, *, -1.0, *, *, *, 0.1, 0.01, -0.55,
           10.0, *, -0.15, 5.0, *, *]
  offdiagonal:
    H-Si: [0.025, 1.4, 10.0, 1.1, *, *]
    O-Si: [0.1,   1.9, 10.0, 1.6, 1.2, *]
  angles:
    H-O-Si:  [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    H-Si-H:  [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    H-Si-O:  [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    H-Si-Si: [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    O-O-Si:  [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    O-Si-O:  [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    O-Si-Si: [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
    Si-O-Si: [20.0, 1.0, 0.5, *, 0.01, *, 1.04]
  torsions:
  hydrogen:
  info: {VdWtype: 'Inner wall, No shielding', branch: combustion, chargeMethod: EEM,
    name: ffield_min}
